# Generated by Django 5.0.2 on 2024-02-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_student_phone_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
